import SideMenu from "@/components/SideMenu/SideMenu";
import "../../styles/globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" className="overflow-hidden debug-screens">
      <body className={cn(inter.className)}>{children}</body>
    </html>
  );
}
