import Sidebar from "@/components/SideBar/Sidebar";
import { ThemeProvider } from "@/components/Theme/ThemeProvider";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html
      lang="en"
      className="overflow-hidden debug-screens"
      suppressHydrationWarning
    >
      <body className={cn(inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="grid grid-cols-12">
            <section className="col-span-2">
              <Sidebar />
            </section>
            <section className="col-span-10 dark:text-white dark:bg-slate-800">
              {children}
            </section>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
